### ISSUE TITLE
Pending Approval

### ISSUE THREAD

**Issue by jasonseminara** [mwerbo2/Climb_Finder#1]
1. This repo name is terrible.
2.  This looks cool. Could you tap into fitbit or iphone data? I'd be happy to let you use that as your api.

**Comment by mwerbo2** [comment]
@jasonseminara 
1. Name updated
2. Throughout this week, I've been struggling to grasp all the moving pieces with MVC and ajax/api calls. Up to this point, I've been struggling with my api (api get limitations). I'd like to get the basics down firm during this project. 

For my MVP: I'm going to go with version one of my proposal:
-  Making a mongodb of the data pulled from the mountain project api (30 - 40 climb locations)
-  Home screen where guests/users can search for climbing routes by location, climb type, and difficulty
-  Authentication page
- User page, allowing users to add comments to climbs (this sounds to be my second model, but I am still confused as to how to actually build out the part that appends the comments to the specific climb, perhaps a update to the database?).
- User page that would show the user's past climbs

**Bonus**
- Adding in a calendar feature that would allow users to signify which day they are going to climb at a location (helps in finding a belay partner)

The end goal is to build confidence with the routing of all information through the MVC and how the functions operate.

**Comment by mwerbo2** [comment]
Approved by Jason 7/1/2016
